// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = {
	/**
	 * Hi this is the stackfront web SHELL with typesafe-i18n as i18n solution.
	 */
	'HEADER': string
}

export type TranslationFunctions = {
	/**
	 * Hi this is the stackfront web SHELL with typesafe-i18n as i18n solution.
	 */
	'HEADER': () => LocalizedString
}

export type Formatters = {}
